apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hellodep
spec:
  replicas: 5
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hellokubctr
        image: daanacohen82/hello
        ports:
        - containerPort: 5000